### ISSUE TITLE
[BUG] BACnet Connector values of multiple controllers being reported to one single device

### ISSUE THREAD

**Issue by granaderainer** [thingsboard/thingsboard-gateway#1785]
**Describe the bug**
Gateway is fetching data from all BACnet Controllers in the network and is mapping this data to the only configured BACnet device in the config.

**Network setup:**
- 4 BACnet controllers

| IP | objectIdentifier |
| --- | --- |
| 192.168.139.23 | 101 |
| 192.168.139.24 | 102 |
| 192.168.139.25 | 103 |
| 192.168.139.26 | 104 |

- thingsboard-gateway
   - 192.168.139.131
   - has configured following device 
     192.168.139.26 - 104

**Issue:**
It seems the gateway receive data from all controllers and uplink all this data to its configured device

For example, Analog Input 3 (see file log.log) is being reported four times with different values at almost the same time (these values are coming from the different BACnet Devices in the network)

![Image](https://github.com/user-attachments/assets/6561febe-a167-41b0-a12e-edc97949a77b)

**Config:**

[config.json](https://github.com/user-attachments/files/20251483/config.json)

**Connector name (If bug in the some connector):**
BACnet-Connector

**Error traceback (If available):**

[log.log](https://github.com/user-attachments/files/20251375/log.log)

**Versions (please complete the following information):**
 - OS:  Docker 3.7.4
 - Thingsboard IoT Gateway version 3.7.4
 - Python version 3.11

**Comment by samson0v** [comment]
Hi @granaderainer, thanks for your interest in ThingsBoard IoT Gateway!
It seems that it is a bug, we will fix it in the nearest future and let you know.

**Comment by samson0v** [comment]
@granaderainer, this bug was fixed. Update the gateway to the latest version using the master branch and let us know about the result.

**Comment by BastiJoe** [comment]
we tried the new code.
although only one device is specified (by IP address) multiple destinations receive the readPropertyRequest from the gateway:

![Image](https://github.com/user-attachments/assets/1b70945c-2632-4782-bcf0-10aac01f70ed)

**Comment by granaderainer** [comment]
@samson0v the issue still exists.
As @BastiJoe wrote it seems the gateway  starts also collecting data of other BACnet controller as soon as they are available and sending a  i-Am Broadcast message.
After a restart of the gateway it is collecting data of just the configured BACnet Controller again until, the second one sends a i-Am Broadcast (e.g. after restart) 

![Image](https://github.com/user-attachments/assets/82844e7b-9b14-4e3f-bdb6-3a5198784208)

**Comment by samson0v** [comment]
@granaderainer, the issue was fixed via [commit](https://github.com/thingsboard/thingsboard-gateway/commit/68cbf08fb92bab496008776ae8478722509d1c82).
Please, try to use the gateway from the master branch and let us know about the result.

**Comment by granaderainer** [comment]
@samson0v tried it with the  current master branch, but still the same.

![Image](https://github.com/user-attachments/assets/38728c3c-0670-462d-9055-9961e2d66f60)

![Image](https://github.com/user-attachments/assets/566ae175-b924-40fd-b88f-f6b9e6d22b93)

**Comment by imbeacon** [comment]
Hi @granaderainer,

Your screenshot - shows different commit, please try to do pull from original thingsboard-gateway repository. Required commit hash is - 68cbf08fb92bab496008776ae8478722509d1c82
